myproject/myapp/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from .import views
app_name = 'myapp'
urlpatterns = [
    path('main_backend_page/', views.main_backend_page, name='main_backend_page'),

    # Room Add
    path('RoomAdd/', views.RoomAdd, name='RoomAdd'),

    # Room List View
    path('RoomListView/', views.RoomListView.as_view(), name='RoomListView'),

    # Room Search View
    path('room_serach/', views.room_serach, name='room_serach'),

    # Room Edit
    path('RoomEdit/<int:pk>/', views.RoomEdit.as_view(), name='RoomEdit'),

    # Room Detail View
    path('RoomListView/<str:pk>/', views.RoomDetailView.as_view(), name='RoomDetailView'),

    path('Reserve/', views.Reserve, name='Reserve'),
    # Reservation List
    path('reservation/', views.ReservationListView.as_view(), name='ReservationListView'),
    # Reservation Detail
    path('ReservationDetailView/<str:pk>/', views.ReservationDetailView.as_view(), name='ReservationDetailView'),


    path('reserve_success/', views.reserve_success, name='reserve_success'),

    # Customer Detail
    path('CustomerDetailView/<str:pk>/', views.CustomerDetailView.as_view(), name='CustomerDetailView'),

    # Staff List
    path('StaffList/', views.StaffList.as_view(), name='StaffList'),

    # Staff Details
    path('StaffDetailView/<str:pk>', views.StaffDetailView.as_view(), name='StaffDetailView'),

    # Staff Add
    path('AddStaff/', views.AddStaff, name='AddStaff'),

    # Staff Edit
    path('StaffEdit/<str:pk>/', views.StaffEdit, name='StaffEdit'),

    # Add Facility
    path('AddFacility/', views.AddFacility, name='AddFacility'),

    # Facility List
    path('FacilityList/', views.FacilityList.as_view(), name='FacilityList'),

    # Facility 
    path('FacilityEdit/<str:pk>/', views.FacilityEdit, name='FacilityEdit'),

    # Room Type List
    path('RoomTypeNameList/', views.RoomTypeNameList.as_view(), name='RoomTypeNameList'),

    # Room Type Detail
    path('RoomTypeDetail/<str:pk>/', views.RoomTypeDetail.as_view(), name='RoomTypeDetail'),

    # Add Room Type name
    path('AddRoomTypeName/', views.AddRoomTypeName, name='AddRoomTypeName'),

    # Edit Room Type name
    path('RoomTypeNameEdit/<str:pk>/', views.RoomTypeNameEdit, name='RoomTypeNameEdit'),


    # RoomType List
    path('RoomTypeList/', views.RoomTypeList.as_view(), name='RoomTypeList'),

    # Add Room Type
    path('AddRoomType/', views.AddRoomType, name='AddRoomType'),

    # Edit Room Type
    path('EditRoomType/<str:pk>/', views.EditRoomType, name='EditRoomType'),
    
    path('signup/', views.signup, name='signup'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

myproject/myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.userlogin, name='userlogin'),
    path('myapp/', include('myapp.urls')),
    path('payment/', include('payment.urls')),
    path('', LoginView.as_view(template_name='Backend/login.html'), name='login'),
    path('users/logout/', LogoutView.as_view(), name='logout'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/myapp/models.py
from django.utils import timezone

from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.db.models.signals import pre_save
from django.urls import reverse
from django.utils.html import format_html
from django.utils.text import slugify
from django.forms import modelformset_factory


class Staff(models.Model):
    staff_id = models.AutoField(primary_key=True)
    # profile_picture = models.ImageField(upload_to="staff_img/%Y/%m/%d",
    #                           default='image/staff.png', verbose_name='Own Picture',
    #                           null=True, blank=True,
    #                           width_field="width_field",
    #                           height_field='height_field')
    # height_field = models.IntegerField(default=0)
    # width_field = models.IntegerField(default=0)
    profile_picture = models.ImageField(upload_to="staff_img", default='image/staff.png', verbose_name='Own Picture')
    first_name = models.CharField(max_length=50)
    middle_name = models.CharField(max_length=50, null=False, blank=True)
    last_name = models.CharField(max_length=50)
    contact_number = models.IntegerField()
    address = models.CharField(max_length=200)
    email_address = models.EmailField()
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True, editable=False)

    class Meta:
        ordering = ["-staff_id"]
        verbose_name = 'Staff'
        verbose_name_plural = 'Staff Information'
        ordering = ['first_name', 'middle_name', 'last_name']
        permissions = (('can_view_staff', "Can view staff"), ('can_view_staff_details', 'Can view staff detail'))

    def __str__(self):
        return '({0}) {1} {2}'.format(self.staff_id, self.first_name, self.last_name)

    def get_absulate_url(self):
        return reverse('myapp:StaffEdit', args=[self.staff_id])


class Customer(models.Model):
    customer_id = models.AutoField(primary_key=True)
    slug = models.SlugField()
    first_name = models.CharField(max_length=50, verbose_name="First Name")
    middle_name = models.CharField(max_length=50, verbose_name="Middle Name", null=False, blank=True)
    last_name = models.CharField(max_length=50, verbose_name="Last Name")
    contact_number = models.IntegerField(verbose_name="Contact Number")
    address = models.CharField(max_length=200, verbose_name="Address")
    email_address = models.EmailField(null=True, blank=True, verbose_name="Email Address")

    class Meta:
        ordering = ['-customer_id']
        verbose_name = "Customer"
        verbose_name_plural = "Customer Information"
        permissions = (('can_view_customer', 'Can view customer'),)

    # def get_absulate_url(self):
    #     return reverse("myapp:post_details", kwargs={"slug": self.slug})

    def __str__(self):
        return '({0} {1} {2})'.format(self.customer_id, self.first_name, self.last_name)

    def my_property(self):
        return self.first_name + ' ' + self.last_name

    my_property.short_description = "Full name of the Person"
    my_property.admin_order_field = 'last_name'
    full_name = property(my_property)


# def create_slug(instance, new_slug=None):
#     slug = slugify(instance.customer_id)
#     if new_slug is not None:
#         slug = new_slug
#     qs = Customer.objects.filter(slug=slug).order_by("-id")
#     exists = qs.exists()
#     if exists:
#         new_slug = "%s-%s" % (slug, qs.first().id)
#         return create_slug(instance, new_slug=new_slug)
#     return slug
#
#
# def pre_save_post_receiver(sender, instance, *args, **kwargs):
#     if not instance.slug:
#         instance.slug = create_slug(instance)
#
#
# pre_save.connect(pre_save_post_receiver, sender=Customer)


############ This is models for reservations ##################
class Reservation(models.Model):
    reservation_id = models.AutoField(primary_key=True)
    # slug = models.SlugField(unique=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, verbose_name='Customer Name')
    staff = models.ForeignKey(Staff, on_delete=models.CharField, editable=False, verbose_name='Staff Name', null=True)
    no_of_adults = models.PositiveIntegerField(default=1, verbose_name='Number of Adult Member')
    no_of_childrens = models.PositiveIntegerField(default=0, verbose_name='Number of Children')
    reservation_date_time = models.DateTimeField(default=timezone.now, verbose_name='Reservation Date Time')
    expected_arrival_date_time = models.DateTimeField(default=timezone.now, verbose_name='Expected Arrival Date Time')
    expected_departure_date_time = models.DateTimeField(default=timezone.now, verbose_name='Expected Departure Date '
                                                                                           'Time')

    class Meta:
        ordering = ["-reservation_id"]
        verbose_name = 'Reservation'
        verbose_name_plural = 'Reservation Information'
        permissions = (('can_view_reservation', 'Can View Reservation'),
                       ('can_view_reservations_default', 'Can view reservation default'),
                       )

    def __str__(self):
        return '({0}) {1}'.format(self.reservation_id, self.customer)

    def colored_name(self):
        return format_html(
            '<span style= "color: #{};"{} {}</span>>',
            self.customer,
            self.no_of_adults,
            self.no_of_childrens,

        )

    def customer_first_name(self, obj):
        return obj.customer.first_name


# def create_slug_for_reservation(instance, new_slug=None):
#     slug = slugify(instance.customer_first_name)
#     if new_slug is not None:
#         slug = new_slug
#     qs = Reservation.objects.filter(slug=slug)
#     exists = qs.exists()
#     if exists:
#         new_slug = "%s-%s" % (slug, qs.first().id)
#         return create_slug_for_reservation(instance, new_slug=new_slug)
#     return slug
#
#
# def pre_save_post_receiver_for_reservation(sender, instance, *args, **kwargs):
#     if not instance.slug:
#         instance.slug = create_slug_for_reservation(instance)
#
#
# pre_save.connect(pre_save_post_receiver_for_reservation, sender=Reservation)


class Facility(models.Model):
    name = models.CharField(max_length=12, verbose_name='Facility Name')
    price = models.PositiveIntegerField(verbose_name='Facility Price')

    def __str__(self):
        return '({0}) {1}'.format(self.name, self.price)

    class Meta:
        ordering = ['-id', '-price']
        verbose_name = 'Facility'
        verbose_name_plural = 'All Facility Information'

################## Room Details Informations ########################
class RoomTypeName(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class RoomCatagory(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class RoomType(models.Model):
    PetType = (
        ('true', 'true'),
        ('false', 'false'),
        )
    
    room_type_id = models.AutoField(primary_key=True) 
    name = models.ForeignKey(RoomTypeName, null=True, on_delete=models.SET_NULL)
    category = models.ForeignKey(RoomCatagory, null=True, on_delete=models.SET_NULL)
    slug = models.SlugField()
    price = models.PositiveIntegerField(verbose_name='Room Price')
    size = models.CharField(max_length=1000, verbose_name='Room Size')
    capacity = models.IntegerField(verbose_name='Capacity')
    pets = models.CharField(max_length=10, choices=PetType, blank=True, default='false')
    breakfast = models.CharField(blank=True, choices=PetType, max_length=10, default='false')
    features = models.CharField(blank=True, choices=PetType, max_length=10, default='false')
    description = models.TextField()
    extras = models.ManyToManyField(Facility)

    def __str__(self):
        return '({0}) {1}'.format(self.name.name, self.category.name)

    class Meta:
        ordering = ['name']
        verbose_name = "RoomType"
        verbose_name_plural = 'All Room Information'

    def my_property(self):
        return self.name.name + ' ' + self.category.name

    my_property.short_description = "Full Slug"
    my_property.admin_order_field = 'category'
    full_slug = property(my_property)

    def display_for_room_facility(self):
        return ', '.join([extras.name for extras in self.extras.all()])

    display_for_room_facility.short_description = 'All Room Facilities'


# def create_slug_for_roomtype(instance, new_slug=None):
#     slug = slugify(instance.name)
#     if new_slug is not None:
#         slug = new_slug
#         qs = RoomType.objects.filter(slug=slug)
#         exists = qs.exists()
#         if exists:
#             new_slug = "%s-%s" % (slug, qs.first().id)
#             return instance.create_slug_for_roomtype(instance, new_slug=new_slug)
#         return slug


# def pre_save_post_receiver_for_roomtypen(sender, instance, *args, **kwargs):
#     if not instance.slug:
#         instance.slug = sender.create_slug_for_roomtype(instance)


# pre_save.connect(pre_save_post_receiver_for_roomtypen, sender=RoomType)


class RoomImage(models.Model):
    room = models.ForeignKey(RoomType, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="room_img/%Y/%m/%d",
                              verbose_name='Room Picture',
                              null=True, blank=True,
                              width_field="width_field",
                              height_field='height_field')
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)


#################################################################################


class Room(models.Model):
    room_no = models.CharField(max_length=10, unique=True, verbose_name='Room Number')
    # slug = models.SlugField()

myproject/templates/Backend/room/room_details.html
{% extends 'Backend/main.html' %}

{% load static %}

{% block title %} Room List{% endblock %}

{% block body %}
  <section>
                    <div class="section-body">
                        <!-- BEGIN DATATABLE 2 -->
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-head style-primary">
                                        <header>Room Type Details</header>
                                        <div class="tools">
                                            <a class="btn btn-icon-toggle btn-collapse"><i class="fa fa-angle-down"></i></a>
                                            <a class="btn btn-icon-toggle btn-close"><i class="md md-close"></i></a>
                                        </div>
                                    </div>
                                    <br>



                            <div class="card-body ">
                                        <div class="table-responsive">
                                   <div class="card-header text-center">
                <!-- Room Photo -->
                {% load static %}
<!--                <img src="#" alt="Room" style="width:200px; height:200px;">-->
            </div>
            <div >Room No = {{ room.room_no }}</div>
            <div >Room Type = {{ room.room_type.name }}({{room.room_type.category}})</div>
            <div >Availability = {% if room.availability %} Yes {% else %} No {% endif %}</div>
            <div>Facilities =  {% for i in room.facility.all %}
                 {{ i.name }}
                {% empty %}
                None
                {% endfor %}
            </div>

            <div >
                {% if room.reservation %}
                    Reservation:
                    <a style="color:blue;" href="{% url 'myapp:ReservationDetailView' room.reservation_id %}" class="text-white">{{ room.reservation }} </a><br/>
                {% endif %}
            </div>



                                      </div>



                                        </div><!--end .table-responsive -->


                                </div>
                            </div><!--end .col -->
                        </div><!--end .row -->
                        <!-- END DATATABLE 2 -->

                    </div><!--end .section-body -->
                </section>



{% endblock %}

myproject/templates/Backend/room/room_list.html
{% extends 'Backend/main.html' %}

{% load static %}

{% block title %} Room List{% endblock %}

{% block body %}


      <section>
                    <div class="section-body">
                        <!-- BEGIN DATATABLE 2 -->
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-head style-primary">
                                        <header>All Room Data</header>
                                        <div class="tools">
                                            <a class="btn btn-icon-toggle btn-collapse"><i class="fa fa-angle-down"></i></a>
                                            <a class="btn btn-icon-toggle btn-close"><i class="md md-close"></i></a>
                                        </div>
                                    </div>
                                    <br>
                                    <a style="padding-left: 20px;" href="{% url 'myapp:RoomTypeNameList' %}"><button type="button" class="btn btn-success">Room Type Name List</button></a>

                                    <a href="{% url 'myapp:FacilityList' %}"><button type="button" class="btn btn-success">Facility List</button></a>

                                    <a href="{% url 'myapp:RoomTypeList' %}"><button type="button" class="btn btn-success">Room Type List</button></a>

                                    <a href="{% url 'myapp:RoomAdd' %}"><button type="button" class="btn btn-success">Room Add</button></a>

                                    {% if room_list %}
                                    <div class="card-body">
                                        <div class="table-responsive">
                                            <table id="datatable2" class="table order-column hover">
                                                <thead>
                                                    <tr>
                                                        <th>Room Number</th>
                                                        <th>Room Type</th>
                                                        <th>Amount</th>
                                                        <th>Facility(Price)</th>
                                                        <th>Availability</th>
                                                        <th width="150px">Buttons</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                     {% for i in room_list %}
                                                        <tr class="gradeX">
                                                            <td>{{i.room_no}}</td>
                                                            <td>{{i.room_type}}</td>
                                                            <td>{{i.room_type.price}}</td>
                                                            <td>
                                                                    {% if i.facility %}
                                                                    {% for j in i.facility.all %}
                                                                    {{j}}
                                                                    {% empty %}
                                                                       None
                                                                    {% endfor %}
                                                                    {% endif %}

                                                            </td>
                                                            <td> 
                                                              {% if i.availability %}
                                                              <span class="badge" style="background: #0aa89e"> Available</span>
                                                              {% else %}
                                                              <span class="badge" style="background: red"> Not Available</span>
                                                              {% endif%}
                                                            </td>
                                                            
                                                            
                                                            <td>
                                                                <a href="{% url 'myapp:RoomEdit' pk=i.pk%}" class="btn ink-reaction btn-floating-action btn-warning"><i class="md md-edit"></i> </a>
                                                                <a href="" class="btn ink-reaction btn-floating-action btn-danger" onclick="return confirm('Are you sure you want to delete this?')"><i class="md md-delete"></i> </a>
                                                                <a href="" class="btn ink-reaction btn-floating-action btn-primary"><i class="md md-print"></i> </a>
                                                            </td>
                                                        </tr>
                                                    {% endfor %}

                                                </tbody>
                                                 <p >Filter By: <a style="color: red;" href="?filter={% if filter == 'all' %}avail{% else %}all{% endif %}">
                                                        {% if filter == 'all' %}
                                                         Available
                                                         {% else %}
                                                         All
                                                        {% endif %}</a></p>
                                                       {% else %}
                                                         <p>There are no rooms.</p>
                                                        {% endif %}

                            {% include 'Backend/room/paginator.html' %}
                                            </table>
                                        </div><!--end .table-responsive -->
                                    </div>   

                                </div>       
                            </div><!--end .col -->
                        </div><!--end .row -->
                        <!-- END DATATABLE 2 -->

                    </div><!--end .section-body -->
                </section>



{% endblock%}

myproject/templates/Backend/room/room_type_list.html
{% extends 'Backend/main.html' %}

{% load static %}

{% block title %} Room List{% endblock %}

{% block body %}


      <section>
                    <div class="section-body">
                        <!-- BEGIN DATATABLE 2 -->
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-head style-primary">
                                        <header>Room Type List</header>
                                        <div class="tools">
                                            <a class="btn btn-icon-toggle btn-collapse"><i class="fa fa-angle-down"></i></a>
                                            <a class="btn btn-icon-toggle btn-close"><i class="md md-close"></i></a>
                                        </div>
                                    </div>
                                    <br>
                                    <a href="{% url 'myapp:AddRoomType' %}"><button type="button" class="btn btn-success">New Room Type Add</button></a>

                                     {% if roomtype_list%}
                                    <div class="card-body">
                                        <div class="table-responsive">
                                            <table id="datatable2" class="table order-column hover">
                                                <thead>
                                                    <tr>

                                                    <th>ID</th>
                                                    <th>Name</th>
                                                    <th>Price</th>
                                                    <th>Size</th>
                                                    <th>Capacity</th>
                                                    <th>Pets</th>
                                                    <th>Breakfast</th>
                                                    
                                                    <th>extras</th>
                                                    <th width="150px">Buttons</th>
                                                        
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                     {% for i in roomtype_list %}
                                                     
                                                        <tr class="gradeX">
                                                           
                                                    <td>{{i.room_type_id}}</td>
                                                    <td>{{i.name}}</td>
                                                    <td>{{i.price}}</td>
                                                    <td>{{i.size}}</td>
                                                    <td>{{i.capacity}}</td>
                                                    <td>{{i.pets}}</td>
                                                    <td>{{i.breakfast}}</td>
                                                    
                                                    <td>
                    
                                                    {% for j in i.extras.all %}
                                                    
                                                       {{j.name}}
                                                       {% if not forloop.last %},{% endif %}
                                                    {% endfor %}
                                                    </td>       
                                                            <td>
                                                                <a href="{% url 'myapp:EditRoomType' i.room_type_id %}" class="btn ink-reaction btn-floating-action btn-warning"><i class="md md-edit"></i> </a>

                                                                 <a href="{% url 'myapp:RoomTypeDetail' i.room_type_id %}" class="btn ink-reaction btn-floating-action btn-warning"><i class="md md-send"></i> </a>
                                                            </td>
                                                          
                                                        </tr>

                                                    {% endfor %}
                                                </tbody>
                                                       {% else %}
                                                         <p>There are no Facility.....</p>
                                                        {% endif %}
                                            </table>
                                        </div><!--end .table-responsive -->
                                    </div>   

                                </div>       
                            </div><!--end .col -->
                        </div><!--end .row -->
                        <!-- END DATATABLE 2 -->

                    </div><!--end .section-body -->
                </section>



{% endblock%}

myproject/templates/Backend/room/room_type_name_list.html
{% extends 'Backend/main.html' %}

{% load static %}

{% block title %} Room List{% endblock %}

{% block body %}


      <section>
                    <div class="section-body">
                        <!-- BEGIN DATATABLE 2 -->
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-head style-primary">
                                        <header>All Room Data</header>
                                        <div class="tools">
                                            <a class="btn btn-icon-toggle btn-collapse"><i class="fa fa-angle-down"></i></a>
                                            <a class="btn btn-icon-toggle btn-close"><i class="md md-close"></i></a>
                                        </div>
                                    </div>
                                    <br>
                                    <a href="{% url 'myapp:AddRoomTypeName' %}"><button type="button" class="btn btn-success">New Room Type Add</button></a>

                                     {% if roomtypename_list%}
                                    <div class="card-body">
                                        <div class="table-responsive">
                                            <table id="datatable2" class="table order-column hover">
                                                <thead>
                                                    <tr>

                                                        <th>Room Type ID</th>
                                                        <th>Room Type Name</th>
                                                        <th width="150px">Buttons</th>
                                                        
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                     {% for i in roomtypename_list %}
                                                        <tr class="gradeX">
                                                            <td>{{i.id}}</td>
                                                            <td>{{i.name}}</td>        
                                                            <td>
                                                                <a href="{% url 'myapp:RoomTypeNameEdit' i.id%}" class="btn ink-reaction btn-floating-action btn-warning"><i class="md md-edit"></i> </a>
                                                            </td>
                                                        </tr>
                                                    {% endfor %}

                                                </tbody>
                                                       {% else %}
                                                         <p>There are no rooms.</p>
                                                        {% endif %}
                                            </table>
                                        </div><!--end .table-responsive -->
                                    </div>   

                                </div>       
                            </div><!--end .col -->
                        </div><!--end .row -->
                        <!-- END DATATABLE 2 -->

                    </div><!--end .section-body -->
                </section>



{% endblock%}