myproject/myapp/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from .import views
app_name = 'myapp'
urlpatterns = [
    path('main_backend_page/', views.main_backend_page, name='main_backend_page'),

    # Room Add
    path('RoomAdd/', views.RoomAdd, name='RoomAdd'),

    # Room List View
    path('RoomListView/', views.RoomListView.as_view(), name='RoomListView'),

    # Room Search View
    path('room_serach/', views.room_serach, name='room_serach'),

    # Room Edit
    path('RoomEdit/<int:pk>/', views.RoomEdit.as_view(), name='RoomEdit'),

    # Room Detail View
    path('RoomListView/<str:pk>/', views.RoomDetailView.as_view(), name='RoomDetailView'),

    path('Reserve/', views.Reserve, name='Reserve'),
    # Reservation List
    path('reservation/', views.ReservationListView.as_view(), name='ReservationListView'),
    # Reservation Detail
    path('ReservationDetailView/<str:pk>/', views.ReservationDetailView.as_view(), name='ReservationDetailView'),


    path('reserve_success/', views.reserve_success, name='reserve_success'),

    # Customer Detail
    path('CustomerDetailView/<str:pk>/', views.CustomerDetailView.as_view(), name='CustomerDetailView'),

    # Staff List
    path('StaffList/', views.StaffList.as_view(), name='StaffList'),

    # Staff Details
    path('StaffDetailView/<str:pk>', views.StaffDetailView.as_view(), name='StaffDetailView'),

    # Staff Add
    path('AddStaff/', views.AddStaff, name='AddStaff'),

    # Staff Edit
    path('StaffEdit/<str:pk>/', views.StaffEdit, name='StaffEdit'),

    # Add Facility
    path('AddFacility/', views.AddFacility, name='AddFacility'),

    # Facility List
    path('FacilityList/', views.FacilityList.as_view(), name='FacilityList'),

    # Facility 
    path('FacilityEdit/<str:pk>/', views.FacilityEdit, name='FacilityEdit'),

    # Room Type List
    path('RoomTypeNameList/', views.RoomTypeNameList.as_view(), name='RoomTypeNameList'),

    # Room Type Detail
    path('RoomTypeDetail/<str:pk>/', views.RoomTypeDetail.as_view(), name='RoomTypeDetail'),

    # Add Room Type name
    path('AddRoomTypeName/', views.AddRoomTypeName, name='AddRoomTypeName'),

    # Edit Room Type name
    path('RoomTypeNameEdit/<str:pk>/', views.RoomTypeNameEdit, name='RoomTypeNameEdit'),


    # RoomType List
    path('RoomTypeList/', views.RoomTypeList.as_view(), name='RoomTypeList'),

    # Add Room Type
    path('AddRoomType/', views.AddRoomType, name='AddRoomType'),

    # Edit Room Type
    path('EditRoomType/<str:pk>/', views.EditRoomType, name='EditRoomType'),
    
    path('signup/', views.signup, name='signup'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

myproject/myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.userlogin, name='userlogin'),
    path('myapp/', include('myapp.urls')),
    path('payment/', include('payment.urls')),
    path('', LoginView.as_view(template_name='Backend/login.html'), name='login'),
    path('users/logout/', LogoutView.as_view(), name='logout'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/payment/urls.py
from django.urls import path
from .import views

app_name = 'payment'
urlpatterns = [
    path('', views.payment_index, name='payment_index'),
    path('CheckinListView', views.CheckinListView.as_view(), name='CheckinListView'),
    path('checkin_show/<str:check_id>', views.checkin_show, name='checkin_show'),
    path('CheckInDetailView/<str:pk>/', views.CheckInDetailView.as_view(), name='CheckInDetailView'),
    path('checkoutList/', views.checkoutList.as_view(), name='checkoutList'),
    path('checkout_show/<str:check_id>', views.checkout_show, name='checkout_show'),
    path('checkoutList/<str:pk>/', views.CheckoutDetails.as_view(), name='CheckoutDetails'),
]

myproject/myapp/models.py
from django.utils import timezone

from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.db.models.signals import pre_save
from django.urls import reverse
from django.utils.html import format_html
from django.utils.text import slugify
from django.forms import modelformset_factory


class Staff(models.Model):
    staff_id = models.AutoField(primary_key=True)
    # profile_picture = models.ImageField(upload_to="staff_img/%Y/%m/%d",
    #                           default='image/staff.png', verbose_name='Own Picture',
    #                           null=True, blank=True,
    #                           width_field="width_field",
    #                           height_field='height_field')
    # height_field = models.IntegerField(default=0)
    # width_field = models.IntegerField(default=0)
    profile_picture = models.ImageField(upload_to="staff_img", default='image/staff.png', verbose_name='Own Picture')
    first_name = models.CharField(max_length=50)
    middle_name = models.CharField(max_length=50, null=False, blank=True)
    last_name = models.CharField(max_length=50)
    contact_number = models.IntegerField()
    address = models.CharField(max_length=200)
    email_address = models.EmailField()
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True, editable=False)

    class Meta:
        ordering = ["-staff_id"]
        verbose_name = 'Staff'
        verbose_name_plural = 'Staff Information'
        ordering = ['first_name', 'middle_name', 'last_name']
        permissions = (('can_view_staff', "Can view staff"), ('can_view_staff_details', 'Can view staff detail'))

    def __str__(self):
        return '({0}) {1} {2}'.format(self.staff_id, self.first_name, self.last_name)

    def get_absulate_url(self):
        return reverse('myapp:StaffEdit', args=[self.staff_id])


class Customer(models.Model):
    customer_id = models.AutoField(primary_key=True)
    slug = models.SlugField()
    first_name = models.CharField(max_length=50, verbose_name="First Name")
    middle_name = models.CharField(max_length=50, verbose_name="Middle Name", null=False, blank=True)
    last_name = models.CharField(max_length=50, verbose_name="Last Name")
    contact_number = models.IntegerField(verbose_name="Contact Number")
    address = models.CharField(max_length=200, verbose_name="Address")
    email_address = models.EmailField(null=True, blank=True, verbose_name="Email Address")

    class Meta:
        ordering = ['-customer_id']
        verbose_name = "Customer"
        verbose_name_plural = "Customer Information"
        permissions = (('can_view_customer', 'Can view customer'),)

    # def get_absulate_url(self):
    #     return reverse("myapp:post_details", kwargs={"slug": self.slug})

    def __str__(self):
        return '({0} {1} {2})'.format(self.customer_id, self.first_name, self.last_name)

    def my_property(self):
        return self.first_name + ' ' + self.last_name

    my_property.short_description = "Full name of the Person"
    my_property.admin_order_field = 'last_name'
    full_name = property(my_property)


# def create_slug(instance, new_slug=None):
#     slug = slugify(instance.customer_id)
#     if new_slug is not None:
#         slug = new_slug
#     qs = Customer.objects.filter(slug=slug).order_by("-id")
#     exists = qs.exists()
#     if exists:
#         new_slug = "%s-%s" % (slug, qs.first().id)
#         return create_slug(instance, new_slug=new_slug)
#     return slug
#
#
# def pre_save_post_receiver(sender, instance, *args, **kwargs):
#     if not instance.slug:
#         instance.slug = create_slug(instance)
#
#
# pre_save.connect(pre_save_post_receiver, sender=Customer)


############ This is models for reservations ##################
class Reservation(models.Model):
    reservation_id = models.AutoField(primary_key=True)
    # slug = models.SlugField(unique=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, verbose_name='Customer Name')
    staff = models.ForeignKey(Staff, on_delete=models.CharField, editable=False, verbose_name='Staff Name', null=True)
    no_of_adults = models.PositiveIntegerField(default=1, verbose_name='Number of Adult Member')
    no_of_childrens = models.PositiveIntegerField(default=0, verbose_name='Number of Children')
    reservation_date_time = models.DateTimeField(default=timezone.now, verbose_name='Reservation Date Time')
    expected_arrival_date_time = models.DateTimeField(default=timezone.now, verbose_name='Expected Arrival Date Time')
    expected_departure_date_time = models.DateTimeField(default=timezone.now, verbose_name='Expected Departure Date '
                                                                                           'Time')

    class Meta:
        ordering = ["-reservation_id"]
        verbose_name = 'Reservation'
        verbose_name_plural = 'Reservation Information'
        permissions = (('can_view_reservation', 'Can View Reservation'),
                       ('can_view_reservations_default', 'Can view reservation default'),
                       )

    def __str__(self):
        return '({0}) {1}'.format(self.reservation_id, self.customer)

    def colored_name(self):
        return format_html(
            '<span style= "color: #{};"{} {}</span>>',
            self.customer,
            self.no_of_adults,
            self.no_of_childrens,

        )

    def customer_first_name(self, obj):
        return obj.customer.first_name


# def create_slug_for_reservation(instance, new_slug=None):
#     slug = slugify(instance.customer_first_name)
#     if new_slug is not None:
#         slug = new_slug
#     qs = Reservation.objects.filter(slug=slug)
#     exists = qs.exists()
#     if exists:
#         new_slug = "%s-%s" % (slug, qs.first().id)
#         return create_slug_for_reservation(instance, new_slug=new_slug)
#     return slug
#
#
# def pre_save_post_receiver_for_reservation(sender, instance, *args, **kwargs):
#     if not instance.slug:
#         instance.slug = create_slug_for_reservation(instance)
#
#
# pre_save.connect(pre_save_post_receiver_for_reservation, sender=Reservation)


class Facility(models.Model):
    name = models.CharField(max_length=12, verbose_name='Facility Name')
    price = models.PositiveIntegerField(verbose_name='Facility Price')

    def __str__(self):
        return '({0}) {1}'.format(self.name, self.price)

    class Meta:
        ordering = ['-id', '-price']
        verbose_name = 'Facility'
        verbose_name_plural = 'All Facility Information'

################## Room Details Informations ########################
class RoomTypeName(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class RoomCatagory(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class RoomType(models.Model):
    PetType = (
        ('true', 'true'),
        ('false', 'false'),
        )
    
    room_type_id = models.AutoField(primary_key=True) 
    name = models.ForeignKey(RoomTypeName, null=True, on_delete=models.SET_NULL)
    category = models.ForeignKey(RoomCatagory, null=True, on_delete=models.SET_NULL)
    slug = models.SlugField()
    price = models.PositiveIntegerField(verbose_name='Room Price')
    size = models.CharField(max_length=1000, verbose_name='Room Size')
    capacity = models.IntegerField(verbose_name='Capacity')
    pets = models.CharField(max_length=10, choices=PetType, blank=True, default='false')
    breakfast = models.CharField(blank=True, choices=PetType, max_length=10, default='false')
    features = models.CharField(blank=True, choices=PetType, max_length=10, default='false')
    description = models.TextField()
    extras = models.ManyToManyField(Facility)

    def __str__(self):
        return '({0}) {1}'.format(self.name.name, self.category.name)

    class Meta:
        ordering = ['name']
        verbose_name = "RoomType"
        verbose_name_plural = 'All Room Information'

    def my_property(self):
        return self.name.name + ' ' + self.category.name

    my_property.short_description = "Full Slug"
    my_property.admin_order_field = 'category'
    full_slug = property(my_property)

    def display_for_room_facility(self):
        return ', '.join([extras.name for extras in self.extras.all()])

    display_for_room_facility.short_description = 'All Room Facilities'


# def create_slug_for_roomtype(instance, new_slug=None):
#     slug = slugify(instance.name)
#     if new_slug is not None:
#         slug = new_slug
#         qs = RoomType.objects.filter(slug=slug)
#         exists = qs.exists()
#         if exists:
#             new_slug = "%s-%s" % (slug, qs.first().id)
#             return instance.create_slug_for_roomtype(instance, new_slug=new_slug)
#         return slug


# def pre_save_post_receiver_for_roomtypen(sender, instance, *args, **kwargs):
#     if not instance.slug:
#         instance.slug = sender.create_slug_for_roomtype(instance)


# pre_save.connect(pre_save_post_receiver_for_roomtypen, sender=RoomType)


class RoomImage(models.Model):
    room = models.ForeignKey(RoomType, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="room_img/%Y/%m/%d",
                              verbose_name='Room Picture',
                              null=True, blank=True,
                              width_field="width_field",
                              height_field='height_field')
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)


#################################################################################


class Room(models.Model):
    room_no = models.CharField(max_length=10, unique=True, verbose_name='Room Number')
    # slug = models.SlugField()

myproject/payment/models.py
from math import ceil

from django.db import models

# Create your models here.
from myapp.models import Reservation, Room

from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User


class CheckIn(models.Model):
    id = models.CharField(max_length=50, primary_key=True, blank=True, editable=True)
    reservation = models.OneToOneField(Reservation, on_delete=models.CASCADE, verbose_name="Reservation")
    rooms = models.CharField(max_length=50, editable=False, blank=True, verbose_name="Room number")
    initial_amount = models.PositiveIntegerField(blank=True, editable=False, verbose_name="Initial Price")
    check_in_date_time = models.DateTimeField(default=timezone.now, editable=False)
    last_edited_on = models.DateTimeField(default=timezone.now, editable=False)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, verbose_name="User name")

    def __str__(self):
        return "%i - %s" % (self.reservation.reservation_id, self.reservation.customer)

    class Meta:
        ordering = ["-id"]
        verbose_name = 'CheckIn'
        verbose_name_plural = 'CheckIn Information'

    def get_absulate_url(self):
        return reverse('payment:CheckInDetailView', args=[self.id])

    def save(self, *args, **kwargs):
        if not self.id:
            self.check_in_date_time = timezone.now()
            self.id = 'Checkin_' + str(self.reservation.reservation_id)
            self.rooms = ', '.join(room.room_no for room in self.reservation.room_set.all())
            self.initial_amount = 0
            for room in self.reservation.room_set.all():
                self.initial_amount += room.room_type.price
                for facility in room.facility.all():
                    self.initial_amount += facility.price

        else:
            reservation = get_object_or_404(CheckIn, id=self.id).resevation
            if self.reservation != reservation:
                self.reservation = reservation

        self.last_edited_on = timezone.now()
        super().save(*args, **kwargs)


class Checkout(models.Model):
    check_in = models.OneToOneField(CheckIn, on_delete=models.CASCADE)
    stay_duration = models.DurationField(null=True, editable=False)
    total_amount = models.PositiveIntegerField(default=0, editable=False)
    pay_amount = models.PositiveIntegerField(default=0, editable=False)
    check_out_date_time = models.DateTimeField(editable=False, null=True)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, editable=False)

    def __str__(self):
        return str(self.id)

    class Meta:
        ordering = ["-check_in"]
        verbose_name = 'Checkout'
        verbose_name_plural = 'CheckOut Information'

    def save(self, *args, **kwargs):
        if not self.id:
            self.check_out_date_time = timezone.now()
            self.stay_duration = self.check_out_date_time - self.check_in.check_in_date_time
            calculate_duration = timezone.timedelta(days=ceil(self.stay_duration.total_seconds() / 3600 / 24))
            self.total_amount = calculate_duration.days * self.check_in.initial_amount
            self.pay_amount = self.total_amount - self.check_in.initial_amount

            super().save(*args, **kwargs)

myproject/templates/Backend/reservation/customer_detail.html
{% extends 'Backend/main.html' %}

{% load static %}

{% block title %} Room List{% endblock %}

{% block body %}



<section>
                    <div class="section-body">
                        <!-- BEGIN DATATABLE 2 -->
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-head style-primary">
                                        <header>Room Type Details</header>
                                        <div class="tools">
                                            <a class="btn btn-icon-toggle btn-collapse"><i class="fa fa-angle-down"></i></a>
                                            <a class="btn btn-icon-toggle btn-close"><i class="md md-close"></i></a>
                                        </div>
                                    </div>
                                    <br>



                            <div class="card-body ">
                                        <div class="table-responsive">
                                   <div class="card-header bg-secondary text-blue"> Customer ID =
            {{ customer.customer_id }}
        </div>

        <div>First Name = {{customer.first_name}}</div>
        <div>{% if customer.middle_name %}
            Middle Name = {{customer.middle_name}}
            {% endif %}
        </div>
        <div>Last Name = {{customer.last_name}}</div>
        <div>Contact Number = {{customer.contact_number}}</div>
        <div>Address = {{customer.address}}</div>
        <div>{% if customer.email_address %}
            Email Address= {{customer.email_address}}
        {% endif %}
        </div>

                                </div>

                                      </div>



                                        </div><!--end .table-responsive -->


                                </div>
                            </div><!--end .col -->
                        </div><!--end .row -->
                        <!-- END DATATABLE 2 -->

                    </div><!--end .section-body -->
                </section>


{% endblock%}

myproject/templates/Backend/reservation/reservation_detail.html
{% extends 'Backend/main.html' %}

{% load static %}

{% block title %} Room List{% endblock %}

{% block body %}

 <section>
                    <div class="section-body">
                        <!-- BEGIN DATATABLE 2 -->
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-head style-primary">
                                        <header>Room Type Details</header>
                                        <div class="tools">
                                            <a class="btn btn-icon-toggle btn-collapse"><i class="fa fa-angle-down"></i></a>
                                            <a class="btn btn-icon-toggle btn-close"><i class="md md-close"></i></a>
                                        </div>
                                    </div>
                                    <br>



                            <div class="card-body ">
                                        <div class="table-responsive">
                                    <div class="card-header bg-secondary text-blue"> Customer Name =
            <a style="color:blue;" href="{% url 'myapp:CustomerDetailView' reservation.customer_id %}">{{ reservation.customer }}</a>
        </div>

        <div>
            {% if reservation.staff %}
            <div class="card-header bg-secondary text-blue"> Staff =
            <a style="color:blue;" href="{% url 'myapp:StaffDetailView' reservation.staff_id %}"> {{reservation.staff}}</a>
            {% else %}
            Staff = {{reservation.staff}}
            </div>
            {% endif %}
        </div>
        <div>Total Number of Adults = {{reservation.no_of_adults}}</div>
        <div>Total Number of Children = {{reservation.no_of_childrens}}</div>
        <div>Reservation Date = {{reservation.reservation_date_time}}</div>
        <div>Expected Arrival Date = {{reservation.expected_arrival_date_time}}</div>
        <div>Expected Departure Date = {{reservation.expected_departure_date_time}}</div>
        <div>
            {% if reservation.room_set.all %}
            Reserved Rooms :
            {% for room in reservation.room_set.all %}
            <strong><a style="color:blue;" href="{% url 'myapp:RoomDetailView' room.id%}">{{room}}</a></strong>
            {% endfor %}
            {% else %}
            None
            {% endif %}
        </div>

                                </div>

                                      </div>



                                        </div><!--end .table-responsive -->


                                </div>
                            </div><!--end .col -->
                        </div><!--end .row -->
                        <!-- END DATATABLE 2 -->

                    </div><!--end .section-body -->
                </section>

{% endblock %}

myproject/templates/Backend/reservation/reservation_list.html
{% extends 'Backend/main.html' %}

{% load static %}

{% block title %} Room List{% endblock %}

{% block body %}

  {% if reservation_list %}
        <form action="{% url 'myapp:ReservationListView' %}" method="POST" id="checkin">
            {% csrf_token %}
        {{ form }}
    </form>

<section>
                    <div class="section-body">
                        <!-- BEGIN DATATABLE 2 -->
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-head style-primary">
                                        <header>All CheckIn List</header>
                                        <div class="tools">
                                            <a class="btn btn-icon-toggle btn-collapse"><i class="fa fa-angle-down"></i></a>
                                            <a class="btn btn-icon-toggle btn-close"><i class="md md-close"></i></a>
                                        </div>
                                    </div>
                                    <br>
                                    <a style="padding-left: 20px;" href="{% url 'payment:CheckinListView' %}"><button type="button" class="btn btn-success">CheckOut?</button></a>

                                    <table class="table table-hover">
                                <thead>
                                <tr>
                                    <th>Reservation ID</th>
                                    <th>Customer</th>
                                    <th>Staff</th>
                                    <th>No of Children</th>
                                    <th>No of Adults</th>
                                    <th>Rooms</th>
                                    <th>Reservation Date Time</th>
                                    <th>Check In?</th>
                                </tr>
                                </thead>
            <tbody>
            {% for reservation in reservation_list %}
                <tr >
                    <td style="text-align: center; ">
                        <a href="{% url 'myapp:ReservationDetailView' reservation.reservation_id%}"> {{ reservation.reservation_id }}</a>
                    </td>
                    <td>{{ reservation.customer }}</td>
                    <td>{{ reservation.staff }}</td>
                    <td style="text-align: center; ">{{ reservation.no_of_childrens }}</td>
                    <td style="text-align: center; ">{{ reservation.no_of_adults }}</td>
                    <td>
                        {% for room in reservation.room_set.all %}
                            {{ room.room_no }}{% if not forloop.last %},{% endif %}
                        {% endfor %}
                    </td>
                    <td>{{ reservation.reservation_date_time }}</td>
                    <td>{% if not reservation.checkin %}
                        <button id="{{ reservation.reservation_id }}" type="button" class="btn btn-primary confirm-checkin"
                                data-toggle="modal"
                                data-target="#checkInConfirmBox">
                            Check-In
                        </button>

                    {% else %}
                        <a style="color:blue;"class="btn btn-secondary"
                           href="{% url 'payment:CheckInDetailView' reservation.checkin.id %}">Details</a>
                    {% endif %}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

         <div class="modal fade" id="checkInConfirmBox">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Confirm Check-In</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <h5>Do you want to confirm check-in?</h5>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-success" form="checkin">
                            Yes
                        </button>
                        <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <p>There are no check-ins.</p>
    {% endif %}

                                        </div><!--end .table-responsive -->
                                    </div>   

                                </div>       
                            </div><!--end .col -->
                        </div><!--end .row -->
                        <!-- END DATATABLE 2 -->

                    </div><!--end .section-body -->
                </section>



<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>  
<script>
        $(document).ready(function () {
            $(".confirm-checkin").click(function () {
                var $id = $(this).attr("id");
                $("#id_reservation").attr("value", $id);
            });
        });
</script>


{% endblock %}

myproject/templates/Backend/reservation/reserve_success_msg.html
{% extends 'Backend/main.html' %}
{% load i18n %}
<h1>Reservation Successful</h1>
{% block desplay %}

    <div class="container">

        <div class="card">
             <div class="card-header bg.success">Reservation ID: {{ reservation.reservation_id }}</div>
            <div class="card-body bg.primary">Customer: <a href="">{{ reservation.customer }}</a>
            </div>
            <div class="card-footer bg.info">Reserved by: <a href="">{{ reservation.staff }}</a></div>
  </div>
</div>
{% endblock %}

myproject/templates/Backend/reservation/staff_detail.html
{% extends 'Backend/main.html' %}

{% load static %}

{% block title %} Room List{% endblock %}

{% block body %}
<section>
                    <div class="section-body">
                        <!-- BEGIN DATATABLE 2 -->
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-head style-primary">
                                        <header>Room Type Details</header>
                                        <div class="tools">
                                            <a class="btn btn-icon-toggle btn-collapse"><i class="fa fa-angle-down"></i></a>
                                            <a class="btn btn-icon-toggle btn-close"><i class="md md-close"></i></a>
                                        </div>
                                    </div>
                                    <br>



                            <div class="card-body ">
                                        <div class="table-responsive">
                                <div class="card-header text-center">
                {% load static %}
                <img src="{{ staff.profile_picture.url }}" alt="Staff Avatar" style="width:200px; height:200px;">
            </div>
            <div >Id =  {{ staff.staff_id }}  </div>
            <div >First Name =  {{ staff.first_name }}  <br>
                                Last Name:  {{ staff.last_name }}  </div>
            <div> Contact No =  {{ staff.contact_number }} </div>
            <div > Address =  {{ staff.address }}</div>
            <!-- Only if staff has email -->
            <div>  {% if staff.email_address %}Email Address =  {{ staff.email_address }} {% endif %}
            </div>

                                </div>

                                      </div>



                                        </div><!--end .table-responsive -->


                                </div>
                            </div><!--end .col -->
                        </div><!--end .row -->
                        <!-- END DATATABLE 2 -->

                    </div><!--end .section-body -->
                </section>

{% endblock %}