myproject/myapp/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from .import views
app_name = 'myapp'
urlpatterns = [
    path('main_backend_page/', views.main_backend_page, name='main_backend_page'),

    # Room Add
    path('RoomAdd/', views.RoomAdd, name='RoomAdd'),

    # Room List View
    path('RoomListView/', views.RoomListView.as_view(), name='RoomListView'),

    # Room Search View
    path('room_serach/', views.room_serach, name='room_serach'),

    # Room Edit
    path('RoomEdit/<int:pk>/', views.RoomEdit.as_view(), name='RoomEdit'),

    # Room Detail View
    path('RoomListView/<str:pk>/', views.RoomDetailView.as_view(), name='RoomDetailView'),

    path('Reserve/', views.Reserve, name='Reserve'),
    # Reservation List
    path('reservation/', views.ReservationListView.as_view(), name='ReservationListView'),
    # Reservation Detail
    path('ReservationDetailView/<str:pk>/', views.ReservationDetailView.as_view(), name='ReservationDetailView'),


    path('reserve_success/', views.reserve_success, name='reserve_success'),

    # Customer Detail
    path('CustomerDetailView/<str:pk>/', views.CustomerDetailView.as_view(), name='CustomerDetailView'),

    # Staff List
    path('StaffList/', views.StaffList.as_view(), name='StaffList'),

    # Staff Details
    path('StaffDetailView/<str:pk>', views.StaffDetailView.as_view(), name='StaffDetailView'),

    # Staff Add
    path('AddStaff/', views.AddStaff, name='AddStaff'),

    # Staff Edit
    path('StaffEdit/<str:pk>/', views.StaffEdit, name='StaffEdit'),

    # Add Facility
    path('AddFacility/', views.AddFacility, name='AddFacility'),

    # Facility List
    path('FacilityList/', views.FacilityList.as_view(), name='FacilityList'),

    # Facility 
    path('FacilityEdit/<str:pk>/', views.FacilityEdit, name='FacilityEdit'),

    # Room Type List
    path('RoomTypeNameList/', views.RoomTypeNameList.as_view(), name='RoomTypeNameList'),

    # Room Type Detail
    path('RoomTypeDetail/<str:pk>/', views.RoomTypeDetail.as_view(), name='RoomTypeDetail'),

    # Add Room Type name
    path('AddRoomTypeName/', views.AddRoomTypeName, name='AddRoomTypeName'),

    # Edit Room Type name
    path('RoomTypeNameEdit/<str:pk>/', views.RoomTypeNameEdit, name='RoomTypeNameEdit'),


    # RoomType List
    path('RoomTypeList/', views.RoomTypeList.as_view(), name='RoomTypeList'),

    # Add Room Type
    path('AddRoomType/', views.AddRoomType, name='AddRoomType'),

    # Edit Room Type
    path('EditRoomType/<str:pk>/', views.EditRoomType, name='EditRoomType'),
    
    path('signup/', views.signup, name='signup'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

myproject/myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.userlogin, name='userlogin'),
    path('myapp/', include('myapp.urls')),
    path('payment/', include('payment.urls')),
    path('', LoginView.as_view(template_name='Backend/login.html'), name='login'),
    path('users/logout/', LogoutView.as_view(), name='logout'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/payment/urls.py
from django.urls import path
from .import views

app_name = 'payment'
urlpatterns = [
    path('', views.payment_index, name='payment_index'),
    path('CheckinListView', views.CheckinListView.as_view(), name='CheckinListView'),
    path('checkin_show/<str:check_id>', views.checkin_show, name='checkin_show'),
    path('CheckInDetailView/<str:pk>/', views.CheckInDetailView.as_view(), name='CheckInDetailView'),
    path('checkoutList/', views.checkoutList.as_view(), name='checkoutList'),
    path('checkout_show/<str:check_id>', views.checkout_show, name='checkout_show'),
    path('checkoutList/<str:pk>/', views.CheckoutDetails.as_view(), name='CheckoutDetails'),
]

myproject/templates/Backend/index.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8" >
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png' %}" >
    <link rel="icon" type="image/png" href="{% static 'assets/img/favicon.png'%}" >
    <meta http-equiv="X-UA-Compatible" content="IE=edge" >

    <title>Power Tech - Administrator</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no' name='viewport' >
    <meta name="viewport" content="width=device-width" >

    <!-- Bootstrap core CSS     -->
    <link href="{% static 'assets/css/bootstrap.min.css'%}" rel="stylesheet" >

    <!--  Paper Dashboard CSS    -->
    <link href="{% static 'assets/css/amaze.css'%}" rel="stylesheet" >

    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="{% static 'assets/css/demo.css'%}" rel="stylesheet" >

        Fonts and icons    
    <link href="{% static 'assets/css/font-awesome.min.css'%}" rel="stylesheet">
    <link href="{% static 'assets/css/font-muli.css'%}" rel='stylesheet' type='text/css'>
    <link href="{% static 'assets/css/themify-icons.css'%}" rel="stylesheet">

    <link href="{% static 'assets/vendors/sweetalert/css/sweetalert2.min.css'%}" rel="Stylesheet" >


</head>


   {% block backend %}

    {% endblock %}
<!--   Core JS Files   -->
<script src="{% static 'assets/vendors/jquery-3.1.1.min.js'%}" type="text/javascript"></script>
<script src="{% static 'assets/vendors/jquery-ui.min.js'%}" type="text/javascript"></script>
<script src="{% static 'assets/vendors/bootstrap.min.js'%}" type="text/javascript"></script>
<script src="{% static 'assets/vendors/material.min.js'%}" type="text/javascript"></script>
<script src="{% static 'assets/vendors/perfect-scrollbar.jquery.min.js'%}" type="text/javascript"></script>
<!-- Forms Validations Plugin -->
<script src="{% static 'assets/vendors/jquery.validate.min.js'%}"></script>
<!--  Plugin for Date Time Picker and Full Calendar Plugin-->
<script src="{% static 'assets/vendors/moment.min.js'%}"></script>
<!--  Charts Plugin -->
<script src="{% static 'assets/vendors/chartist.min.js'%}"></script>
<!--  Plugin for the Wizard -->
<script src="{% static 'assets/vendors/jquery.bootstrap-wizard.js'%}"></script>
<!--  Notifications Plugin    -->
<script src="{% static 'assets/vendors/bootstrap-notify.js'%}"></script>
<!-- DateTimePicker Plugin -->
<script src="{% static 'assets/vendors/bootstrap-datetimepicker.js'%}"></script>
<!-- Vector Map plugin -->
<script src="{% static 'assets/vendors/jquery-jvectormap.js'%}"></script>
<!-- Sliders Plugin -->
<script src="{% static 'assets/vendors/nouislider.min.js'%}"></script>
<!-- Select Plugin -->
<script src="{% static 'assets/vendors/jquery.select-bootstrap.js'%}"></script>
<!--  DataTables.net Plugin    -->
<script src="{% static 'assets/vendors/jquery.datatables.js'%}"></script>
<!-- Sweet Alert 2 plugin -->
<script src="{% static 'assets/vendors/sweetalert/js/sweetalert2.min.js'%}"></script>
<!--	Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
<script src="{% static 'assets/vendors/jasny-bootstrap.min.js'%}"></script>
<!--  Full Calendar Plugin    -->
<script src="{% static 'assets/vendors/fullcalendar.min.js'%}"></script>
<!-- TagsInput Plugin -->
<script src="{% static 'assets/vendors/jquery.tagsinput.js'%}"></script>
<!-- Material Dashboard javascript methods -->
<script src="{% static 'assets/js/amaze.js'%}"></script>
<!-- Material Dashboard DEMO methods, don't include it in your project! -->
<script src="{% static 'assets/js/demo.js'%}"></script>
<script type="text/javascript">
    $().ready(function() {
        demo.checkFullPageBackgroundImage();

        setTimeout(function() {
            // after 1000 ms we add the class animated to the login/register card
            $('.card').removeClass('card-hidden');
        }, 700)
    });
</script>


</html>

myproject/templates/Backend/login.html
<!DOCTYPE html>
{% load static %}
{% load widget_tweaks %}


<html lang="en">
    <head>
        <title>Login | Hotel</title>

        <!-- BEGIN META -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="keywords" content="your,keywords">
        <meta name="description" content="Short explanation about this website">
        <!-- END META -->

        <!-- BEGIN STYLESHEETS -->
        <link href='http://fonts.googleapis.com/css?family=Roboto:300italic,400italic,300,400,500,700,900' rel='stylesheet' type='text/css'/>
        <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
        <link type="text/css" rel="stylesheet" href="{% static 'css/materialadmin.css' %}" />
        <link type="text/css" rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
        <link type="text/css" rel="stylesheet" href="{% static 'css/material-design-iconic-font.min.css' %}" />
        <!-- END STYLESHEETS -->

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
        <script type="text/javascript" src="../../assets/js/libs/utils/html5shiv.js?1403934957"></script>
        <script type="text/javascript" src="../../assets/js/libs/utils/respond.min.js?1403934956"></script>
        <![endif]-->
    </head>
    <body class="menubar-hoverable header-fixed ">

        <!-- BEGIN LOGIN SECTION -->
        <section class="section-account">
            <div class="img-backdrop" style="background-image: url('img/img16.jpg')"></div>
            <!--<div class="spacer"></div>-->
            <div class="card contain-sm style-transparent" style="max-width:450px">
                <div class="card-body">
                    <h2 class="text-center" style="font-size: 40px; margin-bottom: 20px; color: #f70b0b"> HOTEL<br><span style="color: #1ab394; font-weight: 900">Management</span></h2>
                    <br/>
                    <div class="card">
                        <div class="card-body">
                            <span class="text-lg text-bold text-primary">Welcome to our Hotel</span>
                            <br/><br/>
                            <form class="form floating-label" action="{% url 'login' %}" accept-charset="utf-8" method="post">

                                {% csrf_token %}

                                {% if form.errors %}

                                    <div class="alert alert-danger">
                                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                        <strong>Error!</strong> Your username and password didn't match. Please try again.
                                    </div>

                                {% endif %}

                                <div class="form-group">
                                    {{ form.username|add_class:"form-control" }}
                                    <label for="username">Username</label>
                                </div>
                                <div class="form-group">
                                    {{ form.password|add_class:"form-control" }}
                                    <label for="password">Password</label>
                                </div>
                                <br/>
                                <div class="row">
                                    <div class="col-xs-6 text-left">

                                    </div><!--end .col -->

                                    <div class="col-xs-6 text-right">

                                        <button class="btn btn-primary btn-raised" type="submit">Login</button>
                                    </br>
                                        <a style="color:red;"href="{% url 'myapp:signup' %}">New Account</a>
                                    </div><!--end .col -->
                                </div><!--end .row -->
                            </form>
                        </div>
                    </div>
                </div><!--end .card -->
            </div>
            <em class="text-caption text-center" style="margin-bottom: 0px">Copyright © {% now 'Y' %} TAHIYA JAHAN LABONI</em>
            <p class="text-center">BY <strong><span style="color: green">TAHIYA JAHAN</span><span style="color:red"> LABONI</span></strong></p>
        </section>
        <!-- END LOGIN SECTION -->

        <!-- BEGIN JAVASCRIPT -->
        <script src="{% static 'js/libs/jquery/jquery-1.11.2.min.js' %}"></script>
        <script src="{% static 'js/libs/bootstrap/bootstrap.min.js' %}"></script>

        <script src="{% static 'js/core/AppForm.js' %}"></script>
        <!-- END JAVASCRIPT -->

    </body>
</html>

myproject/templates/Backend/main.html
{% load static %}
<html lang="en">
    <head>
        <title>{% block title %} {% endblock %} | Admin Panal</title>

        <!-- BEGIN META -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="keywords" content="your,keywords">
        <meta name="description" content="Short explanation about this website">
        <!-- END META -->

        <!-- BEGIN STYLESHEETS -->
        <link href='http://fonts.googleapis.com/css?family=Roboto:300italic,400italic,300,400,500,700,900' rel='stylesheet' type='text/css'/>
        <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
        <link type="text/css" rel="stylesheet" href="{% static 'css/materialadmin.css' %}" />
        <link type="text/css" rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
        <link type="text/css" rel="stylesheet" href="{% static 'css/material-design-iconic-font.min.css' %}" />
        <link type="text/css" rel="stylesheet" href="{% static 'css/libs/DataTables/jquery.dataTables.css' %}" />
        <link type="text/css" rel="stylesheet" href="{% static 'css/libs/DataTables/extensions/dataTables.colVis.css' %}" />
        <link type="text/css" rel="stylesheet" href="{% static 'css/libs/DataTables/extensions/dataTables.tableTools.css' %}" />
        <link type="text/css" rel="stylesheet" href="{% static 'css/print.css' %}" />
        <!-- END STYLESHEETS -->

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
        <script type="text/javascript" src="../../assets/js/libs/utils/html5shiv.js?1403934957"></script>
        <script type="text/javascript" src="../../assets/js/libs/utils/respond.min.js?1403934956"></script>
        <![endif]-->
    </head>
    <body class="menubar-pin menubar-hoverable header-fixed "> <!--max sidemenu: menubar-pin -->



        <!-- BEGIN HEADER-->
        <header id="header" >
            <div class="headerbar">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="headerbar-left">
                    <ul class="header-nav header-nav-options">
                        <li class="header-nav-brand" >
                            <div class="brand-holder">
                                <a href="{% url 'myapp:main_backend_page' %}">
                                    <span class="text-lg text-light text-danger">HOTEL</span><span class="text-lg text-bold text-primary"> MANAGEMENT</span>
                                </a>
                            </div>
                        </li>
                        <li>
                            <a class="btn btn-icon-toggle menubar-toggle" data-toggle="menubar" href="javascript:void(0);">
                                <i class="fa fa-bars"></i>
                            </a>
                        </li>
                    </ul>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="headerbar-right">
                    <ul class="header-nav header-nav-profile">
                        <li class="dropdown">
                            <a href="javascript:void(0);" class="dropdown-toggle ink-reaction" data-toggle="dropdown">
                                <span class="profile-info">
                                    <h4 class="text-lg text-bold text-primary">Hotel Management</h4>
                                </span>
                            </a>
                            <ul class="dropdown-menu animation-dock">
                                <li class="dropdown-header">My profile</li>
                                <li><a href="">Change Password</a></li>
                                <li class="divider"></li>
                                <li><a href="{% url 'logout' %}"><i class="fa fa-fw fa-power-off text-danger"></i> Logout</a></li>
                            </ul><!--end .dropdown-menu -->
                        </li><!--end .dropdown -->
                    </ul><!--end .header-nav-profile -->
                </div><!--end #header-navbar-collapse -->
            </div>
        </header>
        <!-- END HEADER-->

        <!-- BEGIN BASE-->
        <div id="base">

            <!-- BEGIN OFFCANVAS LEFT -->
            <div class="offcanvas">
            </div><!--end .offcanvas-->
            <!-- END OFFCANVAS LEFT -->

            <!-- BEGIN CONTENT-->
            <div id="content">

            {% if messages %}
                {% for message in messages %}
                    <div {% if message.tags %} class="alert {{ message.tags }} text-center"{% endif %}>
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}

                {% block head_extra %}

                {% endblock head_extra %}

                {% block body %}

                {% endblock %}

            </div><!--end #content-->
            <!-- END CONTENT -->

            <!-- BEGIN MENUBAR-->
            <div id="menubar" class="menubar-inverse ">
                <div class="menubar-fixed-panel">
                    <div>
                        <a class="btn btn-icon-toggle btn-default menubar-toggle" data-toggle="menubar" href="javascript:void(0);">
                            <i class="fa fa-bars"></i>
                        </a>
                    </div>
                    <div class="expanded">
                        <a href="">
                            <span class="text-lg text-bold text-primary ">MATERIAL&nbsp;ADMIN</span>
                        </a>
                    </div>
                </div>
                <div class="menubar-scroll-panel">

                    <!-- BEGIN MAIN MENU -->
                    <ul id="main-menu" class="gui-controls">

                        <!-- BEGIN DASHBOARD -->
                        <li>
                            <a href="{% url 'myapp:main_backend_page' %}" class="active">
                                <div class="gui-icon"><i class="md md-home"></i></div>
                                <span class="title">Dashboard</span>
                            </a>
                        </li><!--end /menu-li -->
                        <!-- END DASHBOARD -->

                        <!-- BEGIN ORDER -->
                        <li class="gui-folder">
                            <a>
                                <div class="gui-icon"><i class="fa fa-shopping-cart"></i></div>
                                <span class="title">Imformation</span>
                            </a>
                            <!--start submenu -->
                            <ul>
                                <li><a href="{% url 'myapp:main_backend_page' %}" ><span class="title">Room Index</span></a></li>
                                <li><a href="{% url 'myapp:RoomListView' %}" ><span class="title">Room Info</span></a></li>
                                <li><a href="{% url 'myapp:ReservationListView' %}" ><span class="title">Reservation Info</span></a></li>

                                <li><a href="{% url 'myapp:Reserve' %}" ><span class="title">Reserve</span></a></li>
                                <li><a href="{% url 'payment:payment_index' %}" ><span class="title">Payment Index</span></a></li>
                                <li><a href="{% url 'payment:CheckinListView' %}" ><span class="title">Check In</span></a></li>
                                <li><a href="{% url 'payment:checkoutList' %}" ><span class="title">Check Out</span></a></li>
                                <li><a href="{% url 'myapp:StaffList' %}" ><span class="title">Staff List</span></a></li>
                            </ul><!--end /submenu -->
                        </li><!--end /menu-li -->
                        <!-- END ORDER -->

                        <!-- BEGIN PROFILE -->
                        <li class="gui-folder">
                            <a>
                                <div class="gui-icon"><i class="fa fa-user"></i></div>
                                <span class="title">Profile</span>
                            </a>
                            <!--start submenu -->
                            <ul>
                                <li><a href="" ><span class="title">Change Password</span></a></li>
                                <li><a href="{% url 'logout' %}" ><span class="title">Logout</span></a></li>
                            </ul><!--end /submenu -->
                        </li><!--end /menu-li -->
                        <!-- END PROFILE -->

                    </ul><!--end .main-menu -->
                    <!-- END MAIN MENU -->

                    <div class="menubar-foot-panel">
                        <small class="no-linebreak hidden-folded">
                            <span class="opacity-75">Copyright &copy; {% now "Y" %}</span> <strong>TAHIYA JAHAN LABONI</strong>
                        </small>
                    </div>
                </div><!--end .menubar-scroll-panel-->
            </div><!--end #menubar-->
            <!-- END MENUBAR -->

        </div><!--end #base-->
        <!-- END BASE -->

        <!-- BEGIN JAVASCRIPT -->
        <script src="{% static 'js/libs/jquery/jquery-1.11.2.min.js' %}"></script>
        <script src="{% static 'js/libs/jquery/jquery-migrate-1.2.1.min.js' %}"></script>
        <script src="{% static 'js/libs/bootstrap/bootstrap.min.js' %}"></script>

        <script src="{% static 'js/libs/nanoscroller/jquery.nanoscroller.min.js' %}"></script>

        <!-- DATATABLE -->
        <script src="{% static 'js/libs/DataTables/jquery.dataTables.min.js' %}"></script>
        <script src="{% static 'js/libs/DataTables/extensions/ColVis/js/dataTables.colVis.min.js' %}"></script>
        <script src="{% static 'js/libs/DataTables/extensions/TableTools/js/dataTables.tableTools.min.js' %}"></script>

        <script src="{% static 'js/core/App.js' %}"></script>
        <script src="{% static 'js/core/AppNavigation.js' %}"></script>
        <script src="{% static 'js/core/AppOffcanvas.js' %}"></script>
        <script src="{% static 'js/core/AppCard.js' %}"></script>
        <script src="{% static 'js/core/AppForm.js' %}"></script>
        <script src="{% static 'js/core/AppVendor.js' %}"></script>
        <script src="{% static 'js/core/Demo.js' %}"></script>
        <script src="{% static 'js/core/DemoTableDynamic.js' %}"></script>
        
        <script
  src="https://code.jquery.com/jquery-1.12.4.min.js"
  integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
  crossorigin="anonymous"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.8.0/marked.min.js"></script>

  <script type="text/javascript">
      $(document).ready(function(){
        $(".content-markdown").each(function(){
            var content = $(this).text()
            var markedContent = marked(content)
            console.log(markedContent)
            $(this).html(markedContent)
        })
        $(".content-markdown img").each(function(){
            $(this).addClass("img-responsive");
        })
      })
  </script>
        <!-- END JAVASCRIPT -->

    </body>
</html>

myproject/templates/Backend/signup.html
 {% extends 'Backend/main.html' %}

{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% block title %} Edit Staff {% endblock %}

{% block body %}
<section>
					<div class="section-body">
						<div class="row">
							<!-- BEGIN  - FORM -->
							<div class="col-lg-12">
								<div class="card">
									<div class="card-head style-primary">

										<header>Add Room</header>
										<div class="tools">
											<a class="btn btn-icon-toggle btn-collapse"><i class="fa fa-angle-down"></i></a>
											<a class="btn btn-icon-toggle btn-close"><i class="md md-close"></i></a>
										</div>
									</div>
									<div class="card-body">

										<form class="form" role="form" action="" method="post"> {% csrf_token %}

											<div class="row">
												<div class="col-sm-6">
													<header>Enter Room Info</header>
													<div class="form-group floating-label">
		                                              	{{ form|crispy }}
														<!-- <label for="name">Enter Facility Name</label> -->
													</div>
												</div>
												

												<div class="col-md-12">
													<hr>
													<div class="card-actionbar-row">
														<input type="submit" class="btn btn-flat btn-primary ink-reaction" value="SUBMIT">
													</div>
												</div>
											</div>
										</form>
									</div><!--end .card-body -->
								</div><!--end .card -->
							</div><!--end .col -->
							<!-- END FORM - TIME ON SITE -->

						</div><!--end .row -->
					</div><!--end .section-body -->
				</section>



{% endblock %}

myproject/templates/Backend/staff_list.html
{% extends 'Backend/main.html' %}

{% load static %}

{% block title %} Room List{% endblock %}

{% block body %}

<section>
                    <div class="section-body">
                        <!-- BEGIN DATATABLE 2 -->
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-head style-primary">
                                        <header>All Room Data</header>
                                        <div class="tools">
                                            <a class="btn btn-icon-toggle btn-collapse"><i class="fa fa-angle-down"></i></a>
                                            <a class="btn btn-icon-toggle btn-close"><i class="md md-close"></i></a>
                                        </div>
                                    </div>
                                    <br>
                                    <a style="padding-left: 20px;" href="{% url 'myapp:AddStaff' %}"><button type="button" class="btn btn-success">New Staff Add</button></a>

                                    
                                     

                                    {% if staff_list %}
                                    <div class="card-body">
                                        <div class="table-responsive">
                                            <table id="datatable2" class="table order-column hover">
                                                <thead>
                                                    <tr>
                                                        <th>ID</th>
                                                    <th>First Name</th>
                                                    <th>Middle Name</th>
                                                    <th>Last Name</th>
                                                    <th>Contact Number</th>
                                                    <th>Address</th>
                                                    <th>Email Address</th>
                                                    <th>Username</th>
                                                        <th width="150px">Buttons</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                     {% for i in staff_list %}
                                                        <tr class="gradeX">
                                                            <td>{{i.staff_id}}</td>
                                                    <td>{{i.first_name}}</td>
                                                    <td>
                                                        {% if i.middle_name %}
                                                    {{i.middle_name}}
                                                    {% else %}
                                                       -
                                                    {% endif %}
                                                   </td>
                                                    <td>{{i.last_name}}</td>
                                                    <td>{{i.contact_number}}</td>
                                                    <td>{{i.address}}</td>
                                                    <td>{{i.email_address}}</td>
                                                    <td>{{i.user}}</td> 
                                                            <td>
                                                                <a href="{{i.get_absulate_url}}" class="btn ink-reaction btn-floating-action btn-warning"><i class="md md-edit"></i> </a>
                                                                <a href="" class="btn ink-reaction btn-floating-action btn-danger" onclick="return confirm('Are you sure you want to delete this?')"><i class="md md-delete"></i> </a>
                                                            </td>
                                                        </tr>
                                                    {% endfor %}

                                                </tbody>
                                                 
                                                       {% else %}
                                                         <p>There are no rooms.</p>
                                                        {% endif %}

                            <!-- {% include 'Backend/room/paginator.html' %} -->
                                            </table>
                                        </div><!--end .table-responsive -->
                                    </div>   

                                </div>       
                            </div><!--end .col -->
                        </div><!--end .row -->
                        <!-- END DATATABLE 2 -->

                    </div><!--end .section-body -->
                </section>


{% endblock %}