myproject/myapp/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from .import views
app_name = 'myapp'
urlpatterns = [
    path('main_backend_page/', views.main_backend_page, name='main_backend_page'),

    # Room Add
    path('RoomAdd/', views.RoomAdd, name='RoomAdd'),

    # Room List View
    path('RoomListView/', views.RoomListView.as_view(), name='RoomListView'),

    # Room Search View
    path('room_serach/', views.room_serach, name='room_serach'),

    # Room Edit
    path('RoomEdit/<int:pk>/', views.RoomEdit.as_view(), name='RoomEdit'),

    # Room Detail View
    path('RoomListView/<str:pk>/', views.RoomDetailView.as_view(), name='RoomDetailView'),

    path('Reserve/', views.Reserve, name='Reserve'),
    # Reservation List
    path('reservation/', views.ReservationListView.as_view(), name='ReservationListView'),
    # Reservation Detail
    path('ReservationDetailView/<str:pk>/', views.ReservationDetailView.as_view(), name='ReservationDetailView'),


    path('reserve_success/', views.reserve_success, name='reserve_success'),

    # Customer Detail
    path('CustomerDetailView/<str:pk>/', views.CustomerDetailView.as_view(), name='CustomerDetailView'),

    # Staff List
    path('StaffList/', views.StaffList.as_view(), name='StaffList'),

    # Staff Details
    path('StaffDetailView/<str:pk>', views.StaffDetailView.as_view(), name='StaffDetailView'),

    # Staff Add
    path('AddStaff/', views.AddStaff, name='AddStaff'),

    # Staff Edit
    path('StaffEdit/<str:pk>/', views.StaffEdit, name='StaffEdit'),

    # Add Facility
    path('AddFacility/', views.AddFacility, name='AddFacility'),

    # Facility List
    path('FacilityList/', views.FacilityList.as_view(), name='FacilityList'),

    # Facility 
    path('FacilityEdit/<str:pk>/', views.FacilityEdit, name='FacilityEdit'),

    # Room Type List
    path('RoomTypeNameList/', views.RoomTypeNameList.as_view(), name='RoomTypeNameList'),

    # Room Type Detail
    path('RoomTypeDetail/<str:pk>/', views.RoomTypeDetail.as_view(), name='RoomTypeDetail'),

    # Add Room Type name
    path('AddRoomTypeName/', views.AddRoomTypeName, name='AddRoomTypeName'),

    # Edit Room Type name
    path('RoomTypeNameEdit/<str:pk>/', views.RoomTypeNameEdit, name='RoomTypeNameEdit'),


    # RoomType List
    path('RoomTypeList/', views.RoomTypeList.as_view(), name='RoomTypeList'),

    # Add Room Type
    path('AddRoomType/', views.AddRoomType, name='AddRoomType'),

    # Edit Room Type
    path('EditRoomType/<str:pk>/', views.EditRoomType, name='EditRoomType'),
    
    path('signup/', views.signup, name='signup'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

myproject/myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.userlogin, name='userlogin'),
    path('myapp/', include('myapp.urls')),
    path('payment/', include('payment.urls')),
    path('', LoginView.as_view(template_name='Backend/login.html'), name='login'),
    path('users/logout/', LogoutView.as_view(), name='logout'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/payment/urls.py
from django.urls import path
from .import views

app_name = 'payment'
urlpatterns = [
    path('', views.payment_index, name='payment_index'),
    path('CheckinListView', views.CheckinListView.as_view(), name='CheckinListView'),
    path('checkin_show/<str:check_id>', views.checkin_show, name='checkin_show'),
    path('CheckInDetailView/<str:pk>/', views.CheckInDetailView.as_view(), name='CheckInDetailView'),
    path('checkoutList/', views.checkoutList.as_view(), name='checkoutList'),
    path('checkout_show/<str:check_id>', views.checkout_show, name='checkout_show'),
    path('checkoutList/<str:pk>/', views.CheckoutDetails.as_view(), name='CheckoutDetails'),
]

myproject/payment/models.py
from math import ceil

from django.db import models

# Create your models here.
from myapp.models import Reservation, Room

from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User


class CheckIn(models.Model):
    id = models.CharField(max_length=50, primary_key=True, blank=True, editable=True)
    reservation = models.OneToOneField(Reservation, on_delete=models.CASCADE, verbose_name="Reservation")
    rooms = models.CharField(max_length=50, editable=False, blank=True, verbose_name="Room number")
    initial_amount = models.PositiveIntegerField(blank=True, editable=False, verbose_name="Initial Price")
    check_in_date_time = models.DateTimeField(default=timezone.now, editable=False)
    last_edited_on = models.DateTimeField(default=timezone.now, editable=False)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, verbose_name="User name")

    def __str__(self):
        return "%i - %s" % (self.reservation.reservation_id, self.reservation.customer)

    class Meta:
        ordering = ["-id"]
        verbose_name = 'CheckIn'
        verbose_name_plural = 'CheckIn Information'

    def get_absulate_url(self):
        return reverse('payment:CheckInDetailView', args=[self.id])

    def save(self, *args, **kwargs):
        if not self.id:
            self.check_in_date_time = timezone.now()
            self.id = 'Checkin_' + str(self.reservation.reservation_id)
            self.rooms = ', '.join(room.room_no for room in self.reservation.room_set.all())
            self.initial_amount = 0
            for room in self.reservation.room_set.all():
                self.initial_amount += room.room_type.price
                for facility in room.facility.all():
                    self.initial_amount += facility.price

        else:
            reservation = get_object_or_404(CheckIn, id=self.id).resevation
            if self.reservation != reservation:
                self.reservation = reservation

        self.last_edited_on = timezone.now()
        super().save(*args, **kwargs)


class Checkout(models.Model):
    check_in = models.OneToOneField(CheckIn, on_delete=models.CASCADE)
    stay_duration = models.DurationField(null=True, editable=False)
    total_amount = models.PositiveIntegerField(default=0, editable=False)
    pay_amount = models.PositiveIntegerField(default=0, editable=False)
    check_out_date_time = models.DateTimeField(editable=False, null=True)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, editable=False)

    def __str__(self):
        return str(self.id)

    class Meta:
        ordering = ["-check_in"]
        verbose_name = 'Checkout'
        verbose_name_plural = 'CheckOut Information'

    def save(self, *args, **kwargs):
        if not self.id:
            self.check_out_date_time = timezone.now()
            self.stay_duration = self.check_out_date_time - self.check_in.check_in_date_time
            calculate_duration = timezone.timedelta(days=ceil(self.stay_duration.total_seconds() / 3600 / 24))
            self.total_amount = calculate_duration.days * self.check_in.initial_amount
            self.pay_amount = self.total_amount - self.check_in.initial_amount

            super().save(*args, **kwargs)

myproject/payment/forms.py
from django import forms
from.models import Checkout

class CheckoutRequest(forms.ModelForm):
    class Meta:
        model = Checkout
        fields = ['check_in']
        widgets = {'check_in': forms.HiddenInput()}
       

myproject/payment/views.py
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db import transaction, IntegrityError
from django.http import Http404
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import DetailView
from myapp.models import Reservation
from django.views import generic

from myapp.models import Facility, Staff
from .forms import CheckoutRequest
from .models import CheckIn, Checkout
from django.urls import reverse


@permission_required("myapp:can_view_staff", login_url='login')
def payment_index(request):
    title = "Payment Dashboard"
    total_reservations = Reservation.objects.all().count()
    total_check_in = CheckIn.objects.all().count()
    # total_check_out = Checkout.objects.all.count()
    last_checked_in = CheckIn.objects.none()
    if total_check_in > 0:
        last_checked_in = CheckIn.objects.get_queryset().latest('check_in_date_time')

    context = {
        'title': title,
        'total_reservations': total_reservations,
        'total_check_in': total_check_in,
        'last_checked_in': last_checked_in,

    }
    return render(request, 'Backend/payment/payment_index.html', context)


class CheckinListView(PermissionRequiredMixin, generic.ListView, generic.FormView):
    model = CheckIn
    # paginate_by = 5
    queryset = CheckIn.objects.all().order_by('-check_in_date_time')
    allow_wmpty = True
    permission_required = 'myapp:can_view_customer'
    title = 'Ckeck In List'
    form_class = CheckoutRequest
    template_name = 'Backend/payment/checkin_list.html'
    extra_context = {
        'title': title,
    }

    def form_valid(self, form):
        try:
            with transaction.atomic():
                checkout = form.save()
                checkout.user = self.request.user
                print(checkout.user)
                checkout.save()
                print(checkout)
                for room in checkout.check_in.reservation.room_set.all():
                    room.reservation = None
                    room.save()
        except IntegrityError:
            raise Http404

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('payment:CheckinListView')


class CheckInDetailView(PermissionRequiredMixin, generic.DetailView):
    model = CheckIn
    template_name = 'Backend/payment/checkin_details.html'
    permission_required = 'myapp:can_view_customer'
    total_facilities = Facility.objects.count()
    title = "CheckIn Detail"

    if not total_facilities:
        facilities = Facility.objects.none()
    else:
        facilities = Facility.objects.all()

    extra_context = {
        'total_facilities': total_facilities,
        'title': title,
        'facilities': facilities,
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        checkin = context['checkin']
        rooms = checkin.rooms
        staff = Staff.objects.filter(user=checkin.user)
        if not staff.count():
            staff = Staff.objects.none()
        else:
            staff = Staff.objects.get(user=checkin.user)

        context['staff'] = staff
        if rooms:
            new_rooms = checkin.rooms.split(", ")
            new_rooms = list(map(int, new_rooms))
            context['rooms'] = new_rooms
        return context


class checkoutList(PermissionRequiredMixin, generic.ListView):
    title = 'Check Out List'
    model = Checkout
    template_name = 'Backend/payment/checkout_list.html'
    # paginate_by = 5
    allow_empty = True
    permission_required = 'myapp:can_view_customer'
    extra_context = {
        'title': title,
    }


class CheckoutDetails(PermissionRequiredMixin, generic.DetailView):
    model = Checkout
    template_name = 'Backend/payment/checkout_detail.html'
    permission_required = 'myapp:can_view_customer'
    title = 'Check Out Detail'
    extra_context = {
        'title':title,
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        checkout = context['checkout']
        staff = Staff.objects.filter(user=checkout.user)
        if not staff.count():
            staff = Staff.objects.none()
        else:
            staff = Staff.objects.get(user=checkout.user)

        context['staff'] = staff
        return context


def checkin_show(request, check_id):
    checkin = CheckIn.objects.filter(id=check_id)
    return render(request, 'Backend/payment/checkin_show.html', {'checkin': checkin})


def checkout_show(request, check_id):
    checkout = Checkout.objects.filter(id=check_id)
    return render(request, 'Backend/payment/checkout_show.html', {'checkout': checkout})

myproject/templates/Backend/payment/checkin_details.html
{% extends 'Backend/main.html' %}

{% load static %}

{% block title %} Room List{% endblock %}

{% block body %}

<section>
                    <div class="section-body">
                        <!-- BEGIN DATATABLE 2 -->
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-head style-primary">
                                        <header>Room Type Details</header>
                                        <div class="tools">
                                            <a class="btn btn-icon-toggle btn-collapse"><i class="fa fa-angle-down"></i></a>
                                            <a class="btn btn-icon-toggle btn-close"><i class="md md-close"></i></a>
                                        </div>
                                    </div>
                                    <br>



                            <div class="card-body ">
                                        <div class="table-responsive">

       <div >Rooms:
            {% for i in rooms %}
                   {{i}}
            {% if not forloop.last %},
            {% endif %}
            {% empty %}
            No Rooms in the reservation.
            {% endfor %}
        </div>
        <div>Amount = {{checkin.initial_amount}}</div>
        <div>Check In Date Time = {{checkin.check_in_date_time}}</div>
        <div>last Edited On = {{checkin.last_edited_on}}</div>
        <div>
            Checked In By: {% if staff.count == 0%}
            {{checkin.user}}
            {% else %}
            <a href="{% url 'myapp:StaffDetailView' staff.staff_id %}">{{staff}}</a>
            {% endif %}
        </div>



                                      </div>



                                        </div><!--end .table-responsive -->


                                </div>
                            </div><!--end .col -->
                        </div><!--end .row -->
                        <!-- END DATATABLE 2 -->

                    </div><!--end .section-body -->
                </section>


{% endblock%}

myproject/templates/Backend/payment/checkin_list.html
{% extends 'Backend/main.html' %}

{% load static %}

{% block title %} Room List{% endblock %}

{% block body %}

  {% if checkin_list %}
        <form action="" method="post" id="checkout">{% csrf_token %}
            {{ form }}
        </form>

<section>
                    <div class="section-body">
                        <!-- BEGIN DATATABLE 2 -->
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-head style-primary">
                                        <header>All CheckIn List</header>
                                        <div class="tools">
                                            <a class="btn btn-icon-toggle btn-collapse"><i class="fa fa-angle-down"></i></a>
                                            <a class="btn btn-icon-toggle btn-close"><i class="md md-close"></i></a>
                                        </div>
                                    </div>
                                    <br>
                                    <a style="padding-left: 20px;" href="{% url 'myapp:ReservationListView' %}"><button type="button" class="btn btn-success">CheckIn?</button></a>

           <div class="card-body">
                                        <div class="table-responsive">
                                    <table class="table table-hover">
            <thead>
            <tr>
                <th>Check-In</th>
                <th>Reservation</th>
                <th>Rooms</th>
                <th>Paid Amount</th>
                <th>Check-In Date Time</th>
                <th>Checkout?</th>
            </tr>
            </thead>
            <tbody>
            {% for check_in in checkin_list %}
                <tr class="gradeX">
                    <td>
                        <a href="{% url 'payment:CheckInDetailView' check_in.id %}"> {{ check_in }}</a>
                    </td>
                    <td>{{ check_in.reservation }}</td>
                    <td>{% if check_in.rooms %}{{ check_in.rooms }}{% else %}-{% endif %}</td>
                    <td>{{ check_in.initial_amount }}</td>
                    <td>{{ check_in.check_in_date_time }}</td>
                    <td>
                        {% if not check_in.checkout %}
                            <button id="{{ check_in.id }}" type="button" class="btn btn-primary confirm-checkout"
                                    data-toggle="modal"
                                    data-target="#checkoutConfirmBox">
                                Checkout
                            </button>

                        {% else %}
<!--                            <a  style="color:blue;" class="btn btn-secondary"-->
<!--                               href="{% url 'payment:CheckInDetailView' check_in.id %}">Details</a>-->
                        <a href="{% url 'payment:CheckInDetailView' check_in.id %}" class="btn ink-reaction btn-floating-action btn-primary"><i class="md md-send"></i> </a>
                        <a href="{% url 'payment:checkin_show' check_in.id %}" class="btn ink-reaction btn-floating-action btn-primary"><i class="md md-print"></i> </a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
                                        </div>
           </div>

        <div class="modal fade" id="checkoutConfirmBox">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Confirm Checkout</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <h5>Do you want to confirm checkout?</h5>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-success" form="checkout">
                            Yes
                        </button>
                        <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <p>There are no check-ins.</p>
    {% endif %}


                                        </div><!--end .table-responsive -->
                                    </div>   

                                </div>       
                            </div><!--end .col -->
                        </div><!--end .row -->
                        <!-- END DATATABLE 2 -->

                    </div><!--end .section-body -->
                </section>


  
       

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>  
 <script>
            $(document).ready(function () {
                $(".confirm-checkout").click(function () {
                    var $id = $(this).attr("id");
                    $("#id_check_in").attr("value", "" + $id);
                });
            });

        </script>



{% endblock %}

myproject/templates/Backend/payment/checkout_detail.html
{% extends 'Backend/main.html' %}

{% load static %}

{% block title %} Room List{% endblock %}

{% block body %}
<section>
                    <div class="section-body">
                        <!-- BEGIN DATATABLE 2 -->
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-head style-primary">
                                        <header>Room Type Details</header>
                                        <div class="tools">
                                            <a class="btn btn-icon-toggle btn-collapse"><i class="fa fa-angle-down"></i></a>
                                            <a class="btn btn-icon-toggle btn-close"><i class="md md-close"></i></a>
                                        </div>
                                    </div>
                                    <br>



                            <div class="card-body ">
                                        <div class="table-responsive">

      <div> Check In :
            <a href="{% url 'payment:CheckInDetailView' checkout.check_in.id %}">{{ checkout.id }}</a>
        </div>
        <div>Stay Duration:
            {{checkout.stay_duration}}
        </div>
        <div>Total Amount = {{checkout.total_amount}}</div>
        <div>Pay Amount = {{checkout.pay_amount}}</div>
        <div>Check Out Date Time = {{checkout.check_out_date_time}}</div>
        <div>
            Checked Out By: {% if staff.count == 0%}
            {{checkout.user}}
            {% else %}
            <a href="{% url 'myapp:StaffDetailView' staff.staff_id %}">{{staff}}</a>
            {% endif %}
        </div>




                                      </div>



                                        </div><!--end .table-responsive -->


                                </div>
                            </div><!--end .col -->
                        </div><!--end .row -->
                        <!-- END DATATABLE 2 -->

                    </div><!--end .section-body -->
                </section>

{% endblock%}

myproject/templates/Backend/payment/checkout_list.html
{% extends 'Backend/main.html' %}

{% load static %}

{% block title %} Room List{% endblock %}

{% block body %}
 <section>
                    <div class="section-body">
                        <!-- BEGIN DATATABLE 2 -->
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-head style-primary">
                                        <header>All Facility</header>
                                        <div class="tools">
                                            <a class="btn btn-icon-toggle btn-collapse"><i class="fa fa-angle-down"></i></a>
                                            <a class="btn btn-icon-toggle btn-close"><i class="md md-close"></i></a>
                                        </div>
                                    </div>
                                    <br>

                                     {% if checkout_list%}
                                    <div class="card-body">
                                        <div class="table-responsive">
                                            <table id="datatable2" class="table order-column hover">
                                                <thead>
                                                <tr>
                                                    <th>Check Out ID</th>
                                                    <th>Related Check In</th>
                                                    <th>Stay Duration</th>
                                                    <th>Total Amount</th>
                                                    <th>Pay Amount</th>
                                                    <th>CheckOut Date Time</th>

                                                </tr>
                                            </thead>

                                                <tbody>
                                                     {% for i in checkout_list %}
                                                        <tr class="gradeX">
                                                            <td>{{i.id}}</td>
                                                    <td><a href="">{{i.check_in}}</a></td>
                                                    <td>{{i.stay_duration}}</td>
                                                    <td>{{i.total_amount}}</td>
                                                    <td>{{i.pay_amount}}</td>
                                                    <td>{{i.check_out_date_time}}</td>
                                                     <td>
<!--                                                         <a style="color:blue;" class="btn btn-secondary"-->
<!--                               href="{% url 'payment:CheckoutDetails' i.id%}">Details</a>-->
                                                         <a href="{% url 'payment:CheckoutDetails' i.id%}" class="btn ink-reaction btn-floating-action btn-primary"><i class="md md-send"></i> </a>
                        <a href="{% url 'payment:checkout_show' i.id %}" class="btn ink-reaction btn-floating-action btn-primary"><i class="md md-print"></i> </a>


                                                     </td>
                                                        </tr>
                                                    {% endfor %}

                                                </tbody>
                                                       {% else %}
                                                         <p>There are no Facility.....</p>
                                                        {% endif %}
                                            </table>
                                        </div><!--end .table-responsive -->
                                    </div>

                                </div>
                            </div><!--end .col -->
                        </div><!--end .row -->
                        <!-- END DATATABLE 2 -->

                    </div><!--end .section-body -->
                </section>



{% endblock %}